### ISSUE TITLE
Thank you for great tutorial

### ISSUE THREAD

**Issue by vinkumdev** [snorristurluson/CustomWidget#1]
I was following your tutorial and it is super super helpful. 

I have very strange issue, when I used copy past code into my project PaletteCategory is not appearing in the Widget blueprint list. Do you have any clue? However when i clone the project i can see category.

I am using 4.26.2, no compile error. Added  dependencies in private module names

`// Uncomment if you are using Slate UI
		 PrivateDependencyModuleNames.AddRange(new string[] { 
			 "Slate", 
			 "SlateCore", 
			 "UMG" ,
			 "DeveloperSettings",
			 "Projects"
		 });`

Any help will be greatly appreciated.

**Comment by snorristurluson** [comment]
Only thing I can think of is something simple, like you might need to regenerate the project file after copying new files into the project. Is the new class showing in the list, just not in the right category? Or is it not showing at all?

**Comment by vinkumdev** [comment]
Hi, very sorry for the silly mistake. I found that I created slice class derived from UUserWidget class rather than Uwidget. Thank you very much for responding :)
